### PR TITLE
pointpats 2.4.0 and proper requirements

### PR DESCRIPTION
**Pull request by martinfleis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #6

Adding new requirements to the recipe.

### CODE REVIEW

**Comment by martinfleis** [comment]
@conda-forge-admin, please rerender

**Comment by martinfleis** [comment]
Hey @weikang9009 and @slumnitz, can any of you merge this one? It supersedes #6 which does not contain an update of requirements.

**Comment by jGaboardi** [comment]
@martinfleis Should we put in our admin requests before or after this PR is merge? And I am curious if the build number should increase for that PR.

**Comment by martinfleis** [comment]
I can include admin rights in this PR, hold on.

> And I am curious if the build number should increase for that PR.

No, there's no 2.4.0 yet. #6 failed.

**Pull request merged**
